name: CI

on: [push]

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        uses: php-actions/composer@v6

      - name: "pint"
        uses: aglipanci/laravel-pint-action@latest
        with:
          testMode: true
          configPath: "./pint.json"

  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        uses: php-actions/composer@v6

      - name: 'phpstan'
        uses: php-actions/phpstan@v3
        with:
          path: src/
